# seeds are generated by Claude, they are for testing purposes

SEED_CATEGORIES = [
    {"name": "Beverages",     "slug": "beverages",     "description": "Soft drinks, juices, water and hot drinks."},
    {"name": "Snacks",        "slug": "snacks",        "description": "Crisps, nuts, confectionery and biscuits."},
    {"name": "Dairy",         "slug": "dairy",         "description": "Milk, cheese, yoghurt and butter."},
    {"name": "Bakery",        "slug": "bakery",        "description": "Bread, pastries and morning goods."},
    {"name": "Produce",       "slug": "produce",       "description": "Fresh fruit and vegetables."},
    {"name": "Household",     "slug": "household",     "description": "Cleaning products and home essentials."},
    {"name": "Frozen",        "slug": "frozen",        "description": "Frozen vegetables, meals and desserts."},
    {"name": "Personal Care", "slug": "personal-care", "description": "Toiletries and grooming."},
    {"name": "Electronics",   "slug": "electronics",   "description": "Phones, tablets, computers"},
]

SEED_SUPPLIERS = [
    {"name": "Acme Foods",            "email": "orders@acmefoods.example",   "phone": "+44 20 7946 0101", "lead_time_days": 3},
    {"name": "Northwind Traders",     "email": "sales@northwind.example",    "phone": "+44 20 7946 0102", "lead_time_days": 7},
    {"name": "Valley Farms",          "email": "hello@valleyfarms.example",  "phone": "+44 20 7946 0103", "lead_time_days": 2},
    {"name": "Crestline Supply",      "email": "orders@crestline.example",   "phone": "+44 20 7946 0104", "lead_time_days": 10},
    {"name": "Harbour Goods",         "email": "contact@harbour.example",    "phone": "+44 20 7946 0105", "lead_time_days": 5},
    {"name": "Pinewood Distributors", "email": "team@pinewood.example",      "phone": "+44 20 7946 0106", "lead_time_days": 14},
]

SEED_PRODUCTS = [
    # --- Beverages ---
    {"sku": "BEV-001", "name": "Bottled Water 500ml",      "category": "Beverages", "supplier": "Acme Foods",            "unit": "EACH",  "cost_price": "0.35", "sale_price": "0.99", "reorder_level": 40, "reorder_quantity": 120, "opening_stock": 120},
    {"sku": "BEV-002", "name": "Orange Juice 1L",          "category": "Beverages", "supplier": "Valley Farms",          "unit": "LITRE", "cost_price": "1.20", "sale_price": "2.49", "reorder_level": 24, "reorder_quantity": 60,  "opening_stock": 18},
    {"sku": "BEV-003", "name": "Cola 330ml Can",           "category": "Beverages", "supplier": "Acme Foods",            "unit": "EACH",  "cost_price": "0.28", "sale_price": "0.85", "reorder_level": 60, "reorder_quantity": 240, "opening_stock": 240},
    {"sku": "BEV-004", "name": "Green Tea Bags 100ct",     "category": "Beverages", "supplier": "Pinewood Distributors", "unit": "BOX",   "cost_price": "2.10", "sale_price": "4.99", "reorder_level": 15, "reorder_quantity": 40,  "opening_stock": 42},
    {"sku": "BEV-005", "name": "Sparkling Water 1L",       "category": "Beverages", "supplier": "Acme Foods",            "unit": "LITRE", "cost_price": "0.55", "sale_price": "1.35", "reorder_level": 30, "reorder_quantity": 90,  "opening_stock": 8},

    # --- Snacks ---
    {"sku": "SNK-001", "name": "Salted Potato Crisps 150g","category": "Snacks",    "supplier": "Northwind Traders",     "unit": "EACH",  "cost_price": "0.75", "sale_price": "1.89", "reorder_level": 50, "reorder_quantity": 150, "opening_stock": 130},
    {"sku": "SNK-002", "name": "Roasted Peanuts 500g",     "category": "Snacks",    "supplier": "Harbour Goods",         "unit": "KG",    "cost_price": "2.40", "sale_price": "4.75", "reorder_level": 20, "reorder_quantity": 50,  "opening_stock": 12},
    {"sku": "SNK-003", "name": "Chocolate Bar 100g",       "category": "Snacks",    "supplier": "Northwind Traders",     "unit": "EACH",  "cost_price": "0.60", "sale_price": "1.49", "reorder_level": 80, "reorder_quantity": 300, "opening_stock": 310},
    {"sku": "SNK-004", "name": "Mixed Nuts 250g",          "category": "Snacks",    "supplier": "Harbour Goods",         "unit": "EACH",  "cost_price": "3.10", "sale_price": "5.99", "reorder_level": 18, "reorder_quantity": 45,  "opening_stock": 45},
    {"sku": "SNK-005", "name": "Pretzel Sticks 200g",      "category": "Snacks",    "supplier": "Northwind Traders",     "unit": "EACH",  "cost_price": "0.90", "sale_price": "2.19", "reorder_level": 25, "reorder_quantity": 60,  "opening_stock": 60},

    # --- Dairy ---
    {"sku": "DRY-001", "name": "Whole Milk 2L",            "category": "Dairy",     "supplier": "Valley Farms",          "unit": "LITRE", "cost_price": "1.10", "sale_price": "2.15", "reorder_level": 40, "reorder_quantity": 100, "opening_stock": 95},
    {"sku": "DRY-002", "name": "Cheddar Cheese Block 400g","category": "Dairy",     "supplier": "Valley Farms",          "unit": "EACH",  "cost_price": "2.80", "sale_price": "5.49", "reorder_level": 20, "reorder_quantity": 50,  "opening_stock": 14},
    {"sku": "DRY-003", "name": "Greek Yoghurt 500g",       "category": "Dairy",     "supplier": "Valley Farms",          "unit": "EACH",  "cost_price": "1.35", "sale_price": "2.79", "reorder_level": 30, "reorder_quantity": 75,  "opening_stock": 72},
    {"sku": "DRY-004", "name": "Salted Butter 250g",       "category": "Dairy",     "supplier": "Crestline Supply",      "unit": "EACH",  "cost_price": "1.60", "sale_price": "3.25", "reorder_level": 25, "reorder_quantity": 60,  "opening_stock": 55},
    {"sku": "DRY-005", "name": "Double Cream 300ml",       "category": "Dairy",     "supplier": "Valley Farms",          "unit": "EACH",  "cost_price": "0.95", "sale_price": "2.10", "reorder_level": 20, "reorder_quantity": 40,  "opening_stock": 6},

    # --- Bakery ---
    {"sku": "BAK-001", "name": "Sourdough Loaf",           "category": "Bakery",    "supplier": "Crestline Supply",      "unit": "EACH",  "cost_price": "1.20", "sale_price": "3.49", "reorder_level": 20, "reorder_quantity": 40,  "opening_stock": 34},
    {"sku": "BAK-002", "name": "Wholemeal Bread 800g",     "category": "Bakery",    "supplier": "Crestline Supply",      "unit": "EACH",  "cost_price": "0.85", "sale_price": "2.29", "reorder_level": 25, "reorder_quantity": 50,  "opening_stock": 40},
    {"sku": "BAK-003", "name": "Croissants 4pk",           "category": "Bakery",    "supplier": "Crestline Supply",      "unit": "BOX",   "cost_price": "1.45", "sale_price": "3.15", "reorder_level": 15, "reorder_quantity": 30,  "opening_stock": 9},
    {"sku": "BAK-004", "name": "Bagels 6pk",               "category": "Bakery",    "supplier": "Harbour Goods",         "unit": "BOX",   "cost_price": "1.30", "sale_price": "2.95", "reorder_level": 15, "reorder_quantity": 30,  "opening_stock": 28},
    {"sku": "BAK-005", "name": "Blueberry Muffins 4pk",    "category": "Bakery",    "supplier": "Crestline Supply",      "unit": "BOX",   "cost_price": "1.75", "sale_price": "3.99", "reorder_level": 12, "reorder_quantity": 24,  "opening_stock": 20},

    # --- Produce ---
    {"sku": "PRD-001", "name": "Bananas",                  "category": "Produce",   "supplier": "Valley Farms",          "unit": "KG",    "cost_price": "0.65", "sale_price": "1.29", "reorder_level": 30, "reorder_quantity": 80,  "opening_stock": 85},
    {"sku": "PRD-002", "name": "Gala Apples",              "category": "Produce",   "supplier": "Valley Farms",          "unit": "KG",    "cost_price": "0.90", "sale_price": "1.85", "reorder_level": 30, "reorder_quantity": 70,  "opening_stock": 64},
    {"sku": "PRD-003", "name": "Baby Spinach 200g",        "category": "Produce",   "supplier": "Valley Farms",          "unit": "EACH",  "cost_price": "0.70", "sale_price": "1.95", "reorder_level": 20, "reorder_quantity": 40,  "opening_stock": 11},
    {"sku": "PRD-004", "name": "Vine Tomatoes",            "category": "Produce",   "supplier": "Valley Farms",          "unit": "KG",    "cost_price": "1.10", "sale_price": "2.45", "reorder_level": 25, "reorder_quantity": 50,  "opening_stock": 48},
    {"sku": "PRD-005", "name": "Avocados",                 "category": "Produce",   "supplier": "Harbour Goods",         "unit": "EACH",  "cost_price": "0.55", "sale_price": "1.39", "reorder_level": 40, "reorder_quantity": 120, "opening_stock": 150},

    # --- Household ---
    {"sku": "HHD-001", "name": "Washing-Up Liquid 750ml",  "category": "Household", "supplier": "Pinewood Distributors", "unit": "EACH",  "cost_price": "0.80", "sale_price": "1.99", "reorder_level": 25, "reorder_quantity": 60,  "opening_stock": 60},
    {"sku": "HHD-002", "name": "Kitchen Roll 4pk",         "category": "Household", "supplier": "Pinewood Distributors", "unit": "BOX",   "cost_price": "1.50", "sale_price": "3.49", "reorder_level": 20, "reorder_quantity": 40,  "opening_stock": 38},
    {"sku": "HHD-003", "name": "Bin Liners 50ct",          "category": "Household", "supplier": "Pinewood Distributors", "unit": "BOX",   "cost_price": "1.10", "sale_price": "2.75", "reorder_level": 20, "reorder_quantity": 40,  "opening_stock": 7},
    {"sku": "HHD-004", "name": "Laundry Detergent 2L",     "category": "Household", "supplier": "Crestline Supply",      "unit": "LITRE", "cost_price": "3.20", "sale_price": "6.99", "reorder_level": 15, "reorder_quantity": 30,  "opening_stock": 26},
    {"sku": "HHD-005", "name": "Multi-Surface Spray 500ml","category": "Household", "supplier": "Pinewood Distributors", "unit": "EACH",  "cost_price": "1.05", "sale_price": "2.39", "reorder_level": 20, "reorder_quantity": 45,  "opening_stock": 44},

    # --- Frozen ---
    {"sku": "FRZ-001", "name": "Garden Peas 1kg",          "category": "Frozen",    "supplier": "Harbour Goods",         "unit": "KG",    "cost_price": "0.95", "sale_price": "2.19", "reorder_level": 25, "reorder_quantity": 60,  "opening_stock": 70},
    {"sku": "FRZ-002", "name": "Fish Fingers 12pk",        "category": "Frozen",    "supplier": "Harbour Goods",         "unit": "BOX",   "cost_price": "1.85", "sale_price": "3.79", "reorder_level": 20, "reorder_quantity": 40,  "opening_stock": 33},
    {"sku": "FRZ-003", "name": "Vanilla Ice Cream 1L",     "category": "Frozen",    "supplier": "Acme Foods",            "unit": "LITRE", "cost_price": "2.20", "sale_price": "4.49", "reorder_level": 18, "reorder_quantity": 36,  "opening_stock": 10},
    {"sku": "FRZ-004", "name": "Oven Chips 1.5kg",         "category": "Frozen",    "supplier": "Harbour Goods",         "unit": "KG",    "cost_price": "1.15", "sale_price": "2.59", "reorder_level": 25, "reorder_quantity": 50,  "opening_stock": 52},
    {"sku": "FRZ-005", "name": "Mixed Berries 500g",       "category": "Frozen",    "supplier": "Valley Farms",          "unit": "EACH",  "cost_price": "2.05", "sale_price": "4.25", "reorder_level": 15, "reorder_quantity": 30,  "opening_stock": 22},

    # --- Personal Care ---
    {"sku": "PCR-001", "name": "Toothpaste 100ml",         "category": "Personal Care", "supplier": "Northwind Traders", "unit": "EACH",  "cost_price": "0.95", "sale_price": "2.49", "reorder_level": 30, "reorder_quantity": 75,  "opening_stock": 88},
    {"sku": "PCR-002", "name": "Shampoo 400ml",            "category": "Personal Care", "supplier": "Northwind Traders", "unit": "EACH",  "cost_price": "1.60", "sale_price": "3.75", "reorder_level": 25, "reorder_quantity": 50,  "opening_stock": 41},
    {"sku": "PCR-003", "name": "Bar Soap 4pk",             "category": "Personal Care", "supplier": "Pinewood Distributors", "unit": "BOX", "cost_price": "1.10", "sale_price": "2.35", "reorder_level": 20, "reorder_quantity": 40, "opening_stock": 5},
    {"sku": "PCR-004", "name": "Deodorant 150ml",          "category": "Personal Care", "supplier": "Northwind Traders", "unit": "EACH",  "cost_price": "1.25", "sale_price": "2.99", "reorder_level": 25, "reorder_quantity": 50,  "opening_stock": 58},
    {"sku": "PCR-005", "name": "Hand Cream 75ml",          "category": "Personal Care", "supplier": "Harbour Goods",     "unit": "EACH",  "cost_price": "1.40", "sale_price": "3.20", "reorder_level": 15, "reorder_quantity": 30,  "opening_stock": 30},
]
